### ISSUE TITLE
cf-pro > File "cf-pro.py", line 3, in <module>

### ISSUE THREAD

**Issue by ProTechEx** [hoaan1995/ZxCDDoS#11]
╚════➤ cf-pro
Traceback (most recent call last):
  File "cf-pro.py", line 3, in <module>
    import os, threading, requests, cloudscraper, datetime, time, socket, socks, ssl, random
ModuleNotFoundError: No module named 'cloudscraper'

**Comment by hoaan1995** [comment]
> ╚════➤ cf-pro Traceback (most recent call last): File "cf-pro.py", line 3, in import os, threading, requests, cloudscraper, datetime, time, socket, socks, ssl, random ModuleNotFoundError: No module named 'cloudscraper'

pip3 install cloudscraper
